[build]
builder = "dockerfile"
# Enable Docker layer caching for faster builds
dockerfilePath = "Dockerfile"
watchPatterns = ["**/*.py", "requirements.txt", "Dockerfile"]
# Enable build caching
cache = true

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
DATA_DIR = "/data"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

[volumes]
data = "/data"
